// gps-maps/src/app/components/azure-map/azure-map.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AzureMapsService } from '../../services/azure-maps.service';
import { LocationService, Location } from '../../services/location.service';
import { HttpClient } from '@angular/common/http';
import { Subscription } from 'rxjs';
import * as atlas from 'azure-maps-control';
import { RoutingService, RouteResponse } from '../../services/routing.service';
import { SearchResponse, SearchResult, SearchService } from '../../services/search.service';


interface RouteInfo {
  distance: number;  // meters
  duration: number;  // seconds
}

@Component({
  selector: 'app-azure-map',
  templateUrl: './azure-map.component.html',
  styleUrls: ['./azure-map.component.css'],
  standalone: true,
  imports: [CommonModule, FormsModule]
})
export class AzureMapComponent implements OnInit, OnDestroy {
  private map: atlas.Map | null = null;
  private dataSource: atlas.source.DataSource | null = null;
  private checkReadyInterval: any;
  private subscriptions: Subscription[] = [];
  private userLocationWatchId: number | null = null;

  // Make these public for template access
  currentLocation: Location | null = null;
  destinationLocation: Location | null = null;
  routeInfo: RouteInfo | null = null;
  searchQuery: string = '';
  searchResults: SearchResult[] = [];

  constructor(
    private azureMapsService: AzureMapsService,
    private locationService: LocationService,
    private routingService: RoutingService,
    private searchService: SearchService
  ) {}

  ngOnInit() {
    this.loadAzureMapsSDK();
   
  }

  private loadAzureMapsSDK() {
    // Load Azure Maps API
    const script = document.createElement('script');
    script.src = 'https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js';
    script.async = true;
    script.defer = true;
    document.head.appendChild(script);

    // Load Azure Maps CSS
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = 'https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css';
    document.head.appendChild(link);

    // Initialize map after SDK loads
    script.onload = () => {
      this.initializeMap();
    };
  }

  private initializeMap() {
    this.map = new atlas.Map('azureMap', {
      authOptions: {
        authType: atlas.AuthenticationType.subscriptionKey,
        subscriptionKey: this.azureMapsService.getSubscriptionKey()
      },
      center: [106.650378,10.801300], // Long, Lat
      zoom: 13,
      style: 'road',
      language: 'vi-VN'
    });

    this.map.events.add('ready', () => {
      // Thêm sprites cho markers
      this.map?.imageSprite.add('marker-red', '/assets/marker-icon-red.png');
      this.map?.imageSprite.add('marker-blue', '/assets/marker-icon.png');

      // Khởi tạo data source cho routing
      this.dataSource = new atlas.source.DataSource();
      this.map?.sources.add(this.dataSource);

      // Thêm layer cho route
      this.map?.layers.add(new atlas.layer.LineLayer(this.dataSource, 'route-layer', {
        strokeColor: '#2272B9',
        strokeWidth: 5
      }));
      
      
    
      this.getCurrentLocation();

      // Subscribe to destination updates
      this.subscribeToLocationUpdates();

      // Thêm click event để đặt điểm đến
      this.map?.events.add('click', (e: atlas.MapMouseEvent) => {
        if (e.position) {
          const destination: Location = {
            lat: e.position[1],
            lng: e.position[0]
          };
          this.locationService.setDestination(destination);
        }
      });
       // Click vào marker kết quả tìm kiếm
    this.map?.events.add('click', (e: atlas.MapMouseEvent) => {
      const position = e.position;
      if (position) {
       
        const destination: Location = {
          lat: position[1],
          lng: position[0]
        };
        this.locationService.setDestination(destination);
      }
    });
    });
    this.searchQuery = "Vườn lài"
    this.onSearch()
  }
  selectSearchResult(result: SearchResult): void {
    const destination: Location = {
      lat: result.coordinates.latitude,
      lng: result.coordinates.longitude
    };
    this.locationService.setDestination(destination);
  }
  
  private getCurrentLocation() {
  
    const location: Location = {
      lat: 10.801300,
      lng: 106.650378
    };
    this.currentLocation = location;
    this.updateCurrentPosition(location);
    this.locationService.updateLocation(location);

    // Start watching position after getting initial location
    // this.startWatchingPosition();
   
  }

  private startWatchingPosition() {
    this.userLocationWatchId = navigator.geolocation.watchPosition(
      (position) => {
        const location: Location = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };
        this.currentLocation = location;
        this.updateCurrentPosition(location);
        this.locationService.updateLocation(location);
      },
      (error) => {
        console.error('Lỗi khi theo dõi vị trí:', error);
      },
      {
        enableHighAccuracy: true,
        timeout: 5000,
        maximumAge: 0
      }
    );
  }

  private subscribeToLocationUpdates() {
    // Subscribe to destination updates
    this.subscriptions.push(
      this.locationService.getDestinationLocation().subscribe(destination => {
        if (destination) {
          this.destinationLocation = destination;
          this.updateMap();
        }
      })
    );
  }

  private updateMap() {
    if (!this.map || !this.dataSource) return;

    // Clear existing data
    this.dataSource.clear();

    // Add current location marker
    if (this.currentLocation) {
      const currentPoint = new atlas.Shape(new atlas.data.Point([
        this.currentLocation.lng,
        this.currentLocation.lat
      ]));
      currentPoint.addProperty('type', 'current');
      this.dataSource.add(currentPoint);

      // Add accuracy circle around current location using a polygon
      const center = [this.currentLocation.lng, this.currentLocation.lat];
      const radius = 100; // meters
      const points = this.createCirclePoints(center, radius);
      const accuracyCircle = new atlas.Shape(new atlas.data.Polygon([points]));
      accuracyCircle.addProperty('type', 'accuracy');
      this.dataSource.add(accuracyCircle);
    }

    // Add destination marker
    if (this.destinationLocation) {
      const destPoint = new atlas.Shape(new atlas.data.Point([
        this.destinationLocation.lng,
        this.destinationLocation.lat
      ]));
      destPoint.addProperty('type', 'destination');
      this.dataSource.add(destPoint);

      // Calculate route if both points exist
      if (this.currentLocation) {
        this.calculateRoute();
      }
    }
// Add search result markers
for (const result of this.searchResults) {
  const marker = new atlas.Shape(new atlas.data.Point([
    result.coordinates.longitude,
    result.coordinates.latitude
  ]));
  marker.addProperty('type', 'search');
  marker.addProperty('id', result.id); // dùng để phân biệt nếu cần
  this.dataSource.add(marker);
}

    // Add layers if not already added
    if (!this.map.layers.getLayerById('symbols')) {
      // Add a symbol layer for the points
      this.map.layers.add(new atlas.layer.SymbolLayer(this.dataSource, 'symbols', {
        iconOptions: {
          image: [
            'case',
            ['==', ['get', 'type'], 'current'],
            'marker-red',
            'marker-blue'
          ],
          anchor: 'bottom',
          size: 1
        },
        filter: ['any', ['==', ['get', 'type'], 'current'], ['==', ['get', 'type'], 'destination']]
      }));

      // Add a fill layer for the accuracy circle
      this.map.layers.add(new atlas.layer.PolygonLayer(this.dataSource, 'accuracy-fill', {
        filter: ['==', ['get', 'type'], 'accuracy'],
        fillColor: 'rgba(0, 102, 255, 0.1)',
      }));

      // Add an outline layer for the accuracy circle
      this.map.layers.add(new atlas.layer.LineLayer(this.dataSource, 'accuracy-outline', {
        filter: ['==', ['get', 'type'], 'accuracy'],
        strokeColor: 'white',
        strokeWidth: 2
      }));
    }
  }

  private createCirclePoints(center: number[], radius: number): number[][] {
    const points: number[][] = [];
    const steps = 64;
    const circumference = 2 * Math.PI;
    const radiusInDegrees = radius / 111000; // approximate degrees per meter at the equator

    for (let i = 0; i <= steps; i++) {
      const angle = (circumference * i) / steps;
      const dx = radiusInDegrees * Math.cos(angle);
      const dy = radiusInDegrees * Math.sin(angle);
      points.push([center[0] + dx, center[1] + dy]);
    }
    return points;
  }

  private calculateRoute() {
    if ( !this.destinationLocation || !this.dataSource) return;

   
    const end: [number, number] = [this.destinationLocation.lat, this.destinationLocation.lng];

    this.routingService.getRoute(end).subscribe({
      next: (response) => {
        if (response.status === 'success' && response.route) {
          // Cập nhật route info
          this.routeInfo = {
            distance: response.route.distance,
            duration: response.route.duration
          };

          // Vẽ tuyến đường
          const coordinates = response.route.points.map(point => [point.longitude, point.latitude]);
          const route = new atlas.data.LineString(coordinates);
          
          // Clear và thêm route mới
          this.dataSource?.clear();
          
          // Thêm lại các markers
          if (this.currentLocation) {
            const currentPoint = new atlas.Shape(new atlas.data.Point([
              this.currentLocation.lng,
              this.currentLocation.lat
            ]));
            currentPoint.addProperty('type', 'current');
            this.dataSource?.add(currentPoint);
          }

          if (this.destinationLocation) {
            const destPoint = new atlas.Shape(new atlas.data.Point([
              this.destinationLocation.lng,
              this.destinationLocation.lat
            ]));
            destPoint.addProperty('type', 'destination');
            this.dataSource?.add(destPoint);
          }

          // Thêm route
          this.dataSource?.add(new atlas.data.Feature(route));

          // Điều chỉnh camera để hiển thị toàn bộ route
          if (this.map) {
            this.map.setCamera({
              bounds: atlas.data.BoundingBox.fromData(route),
              padding: 50
            });
          }
        }
      },
      error: (error) => {
        console.error('Error calculating route:', error);
      }
    });
  }

  private updateCurrentPosition(location: Location): void {
    if (!this.map) return;

    this.map.setCamera({
      center: [location.lng, location.lat],
      zoom: 15,
      type: 'ease',
      duration: 1000
    });

    this.updateMap();
  }

  ngOnDestroy() {
    this.subscriptions.forEach(sub => sub.unsubscribe());
    
    if (this.checkReadyInterval) {
      clearInterval(this.checkReadyInterval);
    }

    if (this.userLocationWatchId !== null) {
      navigator.geolocation.clearWatch(this.userLocationWatchId);
    }

    if (this.map) {
      this.map.dispose();
    }
  }

  onSearch(): void {
    
    if (!this.searchQuery.trim()) return;
    var request = {}
    if (!this.currentLocation) {
       request = {
        query: this.searchQuery,
        
      };
    }
    else {
       request = {
        query: this.searchQuery,
       
      };
    }
   
 
    this.searchService.searchLocation(request).subscribe({
      next: (response: SearchResponse) => {
        if (response.status === 'success' && response.results) {
          this.searchResults = response.results;
          console.log('Kết quả tìm kiếm:', this.searchResults);
        } else {
          console.error('Lỗi tìm kiếm:', response.error);
        }
      },
      error: (error: any) => {
        console.error('Lỗi khi tìm kiếm:', error);
      }
    });
    this.updateMap(); // cập nhật bản đồ sau khi có kết quả mới

  }
}

﻿<div class="map-container">
  <div class="search-box">
    <input type="text"
           [(ngModel)]="searchQuery"
           placeholder="Tìm kiếm địa điểm...">
    <button (click)="onSearch()">Tìm kiếm</button>
   
  </div>
  <div class="search-results" *ngIf="searchResults.length > 0">
    <ul>
      <li *ngFor="let result of searchResults" (click)="selectSearchResult(result)">
        <strong>{{ result.name }}</strong><br>
        <small>{{ result.address }}</small>
      </li>
    </ul>
  </div>
  <div #mapContainer id="azureMap"></div>
  <div class="info-panel" *ngIf="currentLocation || destinationLocation">
    <div class="location-info" *ngIf="currentLocation">
      <h4>Vị trí hiện tại</h4>
      <p>Vĩ độ: {{currentLocation.lat | number:'1.6-6'}}</p>
      <p>Kinh độ: {{currentLocation.lng | number:'1.6-6'}}</p>
    </div>
    <div class="location-info" *ngIf="destinationLocation">
      <h4>Điểm đến</h4>
      <p>Vĩ độ: {{destinationLocation.lat | number:'1.6-6'}}</p>
      <p>Kinh độ: {{destinationLocation.lng | number:'1.6-6'}}</p>
    </div>
    <div class="route-info" *ngIf="routeInfo">
      <h4>Thông tin tuyến đường</h4>
      <p>Khoảng cách: {{(routeInfo.distance / 1000) | number:'1.1-1'}} km</p>
      <p>Thời gian: {{(routeInfo.duration / 60) | number:'1.0-0'}} phút</p>
    </div>
  </div>
</div>

// gps-maps-react/src/components/AzureMap/AzureMap.tsx
import React, { useEffect, useState, useRef, use } from 'react';
import { Location, RouteInfo, SearchResult } from '../../services/types';
import { RoutingService } from '../../services/routing.service';
import { SearchService } from '../../services/search.service';

// Azure Maps subscription key - should be in environment variables
const SUBSCRIPTION_KEY = '';

export const AzureMap: React.FC = () => {
  const mapRef = useRef<atlas.Map | null>(null);
  const dataSourceRef = useRef<atlas.source.DataSource | null>(null);
  const mapContainerRef = useRef<HTMLDivElement>(null);

  const [currentLocation, setCurrentLocation] = useState<Location | null>(null);
  const [destinationLocation, setDestinationLocation] = useState<Location | null>(null);
  const [routeInfo, setRouteInfo] = useState<RouteInfo | null>(null);
  const [searchQuery, setSearchQuery] = useState<string>("Vườn lài");
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const [isMapReady, setIsMapReady] = useState(false);
  const [sdkLoaded, setSdkLoaded] = useState(false);

 
  useEffect(() => {
    const existingScript = document.getElementById('azure-maps-sdk');
    if (existingScript) {
      setSdkLoaded(true);
      return;
    }

    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = 'https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.css';
    document.head.appendChild(link);

    const script = document.createElement('script');
    script.id = 'azure-maps-sdk';
    script.src = 'https://atlas.microsoft.com/sdk/javascript/mapcontrol/2/atlas.min.js';
    script.async = true;
    script.onload = () => setSdkLoaded(true);
    document.head.appendChild(script);

    return () => {
      if (mapRef.current) {
        mapRef.current.dispose();
      }
    };
  }, []);

  useEffect(() => {
    if (!sdkLoaded || !mapContainerRef.current || mapRef.current) return;

    mapRef.current = new atlas.Map('azureMap', {
      authOptions: {
        authType: atlas.AuthenticationType.subscriptionKey,
        subscriptionKey: SUBSCRIPTION_KEY
      },
      center: [106.650378, 10.801300],
      zoom: 13,
      style: 'road',
      language: 'vi-VN'
    });

    mapRef.current.events.add('ready', () => {
      setIsMapReady(true);
    });
  }, [sdkLoaded]);

  useEffect(() => {
    if (!isMapReady || !mapRef.current) return;

    dataSourceRef.current = new atlas.source.DataSource();
    mapRef.current.sources.add(dataSourceRef.current);

    mapRef.current.layers.add(new atlas.layer.LineLayer(dataSourceRef.current, 'route-layer', {
      strokeColor: '#2272B9',
      strokeWidth: 5
    }));

    // Layer cho điểm ban đầu
    mapRef.current.layers.add(new atlas.layer.SymbolLayer(dataSourceRef.current, 'start-symbol', {
      filter: ['==', ['get', 'type'], 'current'],
      iconOptions: {
        anchor: 'bottom',
        allowOverlap: true,
        image: 'pin-blue'
      }
    }));

    // Layer cho điểm đến với màu đỏ
    mapRef.current.layers.add(new atlas.layer.SymbolLayer(dataSourceRef.current, 'destination-symbol', {
      filter: ['==', ['get', 'type'], 'destination'],
      iconOptions: {
        anchor: 'bottom',
        allowOverlap: true,
        image: 'pin-red'
      }
    }));

    mapRef.current.events.add('click', (e: atlas.MapMouseEvent) => {
      if (e.position) {
        const destination: Location = {
          lat: e.position[1],
          lng: e.position[0]
        };
        setDestinationLocation(destination);
      }
    });

    getCurrentLocation();
  }, [isMapReady]);
  const initialMarkerRef = useRef<atlas.Shape | null>(null);

  useEffect(() => {
    if (!isMapReady || !dataSourceRef.current) return;
    
    initialMarkerRef.current = new atlas.Shape(new atlas.data.Point([
      106.650378,
      10.801300
    ]));
    initialMarkerRef.current.addProperty('type', 'current');
    
    dataSourceRef.current.add(initialMarkerRef.current);
  }, [isMapReady]);
  useEffect(() => {
    if (isMapReady && currentLocation) {
      handleSearch();
    }
  }, [isMapReady, currentLocation]);

  const getCurrentLocation = () => {
    const location: Location = {
      lat: 10.801300,
      lng: 106.650378
    };
    setCurrentLocation(location);
    updateMap(location, destinationLocation);
  };

  const handleSearch = async () => {
    if (!searchQuery.trim() || !isMapReady) return;

    try {
      const response = await SearchService.searchLocation({ query: searchQuery });
      if (response.status === 'success' && response.results) {
        setSearchResults(response.results);
        updateMap(currentLocation, destinationLocation);
      }
    } catch (error) {
      console.error('Lỗi khi tìm kiếm:', error);
    }
  };

  const calculateRoute = async () => {
    if (!currentLocation || !destinationLocation || !dataSourceRef.current || !isMapReady) return;

    const end: [number, number] = [destinationLocation.lat, destinationLocation.lng];

    try {
      const response = await RoutingService.getRoute(end);
      if (response.status === 'success' && response.route) {
        setRouteInfo({
          distance: response.route.distance,
          duration: response.route.duration
        });

        const coordinates = response.route.points.map(point => [point.longitude, point.latitude]);
        const route = new atlas.Shape(new atlas.data.LineString(coordinates));

        // dataSourceRef.current.clear();
        dataSourceRef.current.add(route);
        // Thêm marker điểm đích sau khi vẽ route
        addMarkers();

        if (mapRef.current) {
          mapRef.current.setCamera({
            bounds: atlas.data.BoundingBox.fromData(route),
            padding: 50
          });
        }
      }
    } catch (error) {
      console.error('Error calculating route:', error);
    }
  };

  const addMarkers = () => {
    if (!dataSourceRef.current || !isMapReady) return;

    // Thêm marker điểm đích nếu có
    if (destinationLocation) {
      const destPoint = new atlas.Shape(new atlas.data.Point([
        destinationLocation.lng,
        destinationLocation.lat
      ]));
      destPoint.addProperty('type', 'destination');
      dataSourceRef.current.add(destPoint);
    }
  };

  const updateMap = (
    current: Location | null, 
    destination: Location | null
  ) => {
    if (!mapRef.current || !dataSourceRef.current || !isMapReady) return;

    dataSourceRef.current.clear();
    if (initialMarkerRef.current) {
      dataSourceRef.current.add(initialMarkerRef.current);
    }
    
    if (current) {
      mapRef.current.setCamera({
        center: [current.lng, current.lat],
        zoom: 15,
        type: 'ease',
        duration: 1000
      });
    }

    addMarkers();
  };

  useEffect(() => {
    if (destinationLocation && isMapReady) {
      calculateRoute();
    }
  }, [destinationLocation, isMapReady]);

  return (
    <div className="azure-map-container">
      <div id="azureMap" ref={mapContainerRef} style={{ width: '100%', height: '100%' }} />
      <div className="search-container">
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Tìm kiếm địa điểm..."
        />
        <button onClick={handleSearch}>Tìm kiếm</button>
      </div>
      {searchResults.length > 0 && (
        <div className="search-results">
          {searchResults.map(result => (
            <div
              key={result.id}
              onClick={() => setDestinationLocation({
                lat: result.coordinates.latitude,
                lng: result.coordinates.longitude
              })}
              className="search-result-item"
            >
              <div key={`name-${result.id}`} className="result-name">{result.name}</div>
              {result.address && (
                <div key={`address-${result.id}`} className="result-address">{result.address}</div>
              )}
            </div>
          ))}
        </div>
      )}
      {routeInfo && (
        <div className="route-info">
          <p>Khoảng cách: {(routeInfo.distance / 1000).toFixed(2)} km</p>
          <p>Thời gian: {Math.round(routeInfo.duration / 60)} phút</p>
        </div>
      )}
    </div>
  );
};
